name: podchet_kalloriy
description: Приложение подсчёта калорий с ИИ-рекомендациями
publish_to: 'none'
version: 1.4.5+16

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^0.4.2+4
  path: ^1.9.0
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.35.5
  pp_bluetooth_kit_flutter:
    git:
      url: https://github.com/LefuHengqi/pp_bluetooth_kit_flutter.git
      ref: 0.0.51
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lefu.config
    - assets/lefu_credentials.json
    - assets/lefu_device.json
